#!/bin/bash

echo "Trajectories should be put in subdirectories 'film_trajectories/<T>K_<pairs>A'"

temperatures=(200 250 300 350 400)
il_pair_counts=(54 54 54 154 154)
alu_count=(14592 14952 14952 58368 58368)
oxy_count=(20736 20736 20736 82944 82944)
ohy_count=(2304 2304 2304 9216 9216)
frame_indices=(0 1500 0 0 0)

# IL type: C2Mim NTF2
cation_atoms=19
anion_atoms=15

# distance in nanometer for particles to be considered touching
cutoff_distance=1.3
# minimal number of vertices a hole needs to have to be considered a hole and not a face of the film
minimal_hole_vertex_count=5

for i in "${!temperatures[@]}"; do
	temperature=${temperatures[i]}
	il_pair_count=${il_pair_counts[i]}
	frame_index=${frame_indices[i]}

	indir=film_trajectories/${temperature}K_${il_pair_count}A
	partialsdir=${indir}/partial/

	trajectory_src=${indir}/nvt.xtc
	period_out=${partialsdir}/pbc.period
	cation_partial_xtc=${partialsdir}/cation_com.xtc
	cation_partial_traj=${partialsdir}/cation_com.traj
	anion_partial_xtc=${partialsdir}/anion_com.xtc
	anion_partial_traj=${partialsdir}/anion_com.traj

	output_dir="./results/morphology/${temperature}K_${il_pair_count}A/"
	mkdir -p ${output_dir}

	echo "Processing trajectories in ${indir} and outputting dumped graphs to ${output_dir} ..."

	# Calcualte area and perimeter statistics of the film
	./planar_bin/extractFilmParams -i1 ${cation_partial_xtc} -i2 ${anion_partial_xtc} -o ${output_dir}/film_ -c ${cutoff_distance} -hl ${minimal_hole_vertex_count} -d 1 -df ${frame_index} &
done

exit 0
